export const ADD_SERVICE_TO_CART_REQUEST = "ADD_SERVICE_TO_CART_REQUEST";
export const ADD_SERVICE_TO_CART_SUCCESS = "ADD_SERVICE_TO_CART_SUCCESS";
export const ADD_SERVICE_TO_CART_FAIL = "ADD_SERVICE_TO_CART_FAIL";

export const GET_SERVICES_IN_CART_REQUEST = "GET_SERVICES_IN_CART_REQUEST";
export const GET_SERVICES_IN_CART_SUCCESS = "GET_SERVICES_IN_CART_SUCCESS";
export const GET_SERVICES_IN_CART_FAIL = "GET_SERVICES_IN_CART_FAIL";

export const DELETE_SERVICES_IN_CART_REQUEST = "DELETE_SERVICES_IN_CART_REQUEST";
export const DELETE_SERVICES_IN_CART_SUCCESS = "DELETE_SERVICES_IN_CART_SUCCESS";
export const DELETE_SERVICES_IN_CART_FAIL = "DELETE_SERVICES_IN_CART_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";