export const PLACE_SERVICE_ORDER_REQUEST = "PLACE_SERVICE_ORDER_REQUEST";
export const PLACE_SERVICE_ORDER_SUCCESS = "PLACE_SERVICE_ORDER_SUCCESS";
export const PLACE_SERVICE_ORDER_FAIL = "PLACE_SERVICE_ORDER_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const ACCEPT_OR_REJECT_ORDER_REQUEST = "ACCEPT_OR_REJECT_ORDER_REQUEST";
export const ACCEPT_OR_REJECT_ORDER_SUCCESS = "ACCEPT_OR_REJECT_ORDER_SUCCESS";
export const ACCEPT_OR_REJECT_ORDER_FAIL = "ACCEPT_OR_REJECT_ORDER_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_AN_ORDER_DETAILS_REQUEST = "GET_AN_ORDER_DETAILS_REQUEST";
export const GET_AN_ORDER_DETAILS_SUCCESS = "GET_AN_ORDER_DETAILS_SUCCESS";
export const GET_AN_ORDER_DETAILS_FAIL = "GET_AN_ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";