export const GET_ALL_PROFESSIONALS_REQUEST = "GET_ALL_PROFESSIONALS_REQUEST";
export const GET_ALL_PROFESSIONALS_SUCCESS = "GET_ALL_PROFESSIONALS_SUCCESS";
export const GET_ALL_PROFESSIONALS_FAIL = "GET_ALL_PROFESSIONALS_FAIL";

export const GET_A_PROFESSIONAL_REQUEST = "GET_A_PROFESSIONAL_REQUEST";
export const GET_A_PROFESSIONAL_SUCCESS = "GET_A_PROFESSIONAL_SUCCESS";
export const GET_A_PROFESSIONAL_FAIL = "GET_A_PROFESSIONAL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";