export const NEW_SERVICE_REQUEST = "NEW_SERVICE_REQUEST";
export const NEW_SERVICE_SUCCESS = "NEW_SERVICE_SUCCESS";
export const NEW_SERVICE_RESET = "NEW_SERVICE_RESET";
export const NEW_SERVICE_FAIL = "NEW_SERVICE_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

export const GET_ALL_SERVICES_REQUEST = "GET_ALL_SERVICES_REQUEST";
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS";
export const GET_ALL_SERVICES_FAIL = "GET_ALL_SERVICES_FAIL";

export const GET_A_SERVICE_DETAIL_REQUEST = "GET_A_SERVICE_DETAIL_REQUEST";
export const GET_A_SERVICE_DETAIL_SUCCESS = "GET_A_SERVICE_DETAIL_SUCCESS";
export const GET_A_SERVICE_DETAIL_FAIL = "GET_A_SERVICE_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";